#!/bin/bash

function print_logo() {
 echo "WIP" 
}

function generate_final_code() {
  tr -dc A-Za-z0-9 </dev/urandom | head -c 64 > .utils/temp/code
}

print_logo
./reset
generate_final_code
cd .utils
./generate_tree.sh
echo "Connection au réseau.."
sleep .8
./random_file.sh
echo "Connecté !"
./enigme_0.sh
exec -a firewall_9000_super_secure ./firewall_9000_super_secure &
