#!/bin/bash

function print_logo() {
 echo "WIP" 
}

function generate_final_code() {
  tr -dc A-Za-z0-9 </dev/urandom | head -c 64 > .utils/temp/code
}

print_logo
./reset
generate_final_code
./.utils/generate_tree.sh
./.utils/random_file.sh
